name: publish on osi.run when push to main

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: osi.run

    steps:
    - name: stop osi service
      run: sudo /bin/systemctl stop osi.service
    - name: snapshot filesystem
      run: sudo snapper -c root create
    - name: git pull
      run: git  -C /home/fyksen/Activities/ pull
    - name: dotnet publish
      run: cd /home/fyksen/Activities/Activities.Web/ && exec dotnet publish
    - name: start osi service
      run: sudo /bin/systemctl start osi.service
    - name: Make a log post
      run: date >> /home/fyksen/git-update.log | echo "Ran git pull" >> /home/fyksen/git-update.log
