name: publish on osi.run when push to main

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: osi.run

    steps:
    - name: stop osi service
      run: sudo /bin/systemctl stop osi.service
    - name: snapshot filesystem
      run: ssh 192.168.0.10 /usr/sbin/btrfs subvolume snapshot -r /data/osirun/ /data/osirun/.$(date +%Y-%m-%d-%T)
    - name: git pull
      run: git  -C /data/osirun/Activities/ pull
    - name: dotnet publish
      run: cd /data/osirun/Activities/Activities.Web/ && exec dotnet publish
    - name: start osi service
      run: sudo /bin/systemctl start osi.service
    - name: Make a log post
      run: date >> /data/persistant/log.txt | echo "Ran git pull" >> /data/persistant/log.txt
